version: '3'

services:
  web:
    build: ./youtube
    command: gunicorn youtube.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - ./youtube:/youtube
#      - ./youtube/static:/static
#      - ./youtube/media:/media
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
#    volumes:
#      - ./youtube/static:/static
#      - ./youtube/media:/media
